# Generated by Django 3.2.3 on 2022-08-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='账号名称')),
                ('app_id', models.CharField(max_length=50, verbose_name='开发者ID')),
                ('app_secret', models.CharField(blank=True, default='', max_length=150, verbose_name='开发者密码')),
                ('status', models.SmallIntegerField(choices=[(-1, '已失效'), (0, '待生效'), (1, '生效中')], default=0, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '微信账号管理',
                'verbose_name_plural': '微信账号管理',
                'db_table': 'wx_account',
            },
        ),
    ]
