# Generated by Django 3.2.3 on 2022-08-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
