# Generated by Django 3.2.3 on 2022-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20220808_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxaccountmodel',
            name='ename',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='app_secret',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='开发者密钥'),
        ),
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '已失效'), (0, '待生效'), (1, '生效中')], db_index=True, default=0, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='wxaccountmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
