# Generated by Django 3.2.3 on 2022-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_auto_20220808_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxaccountmodel',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '未注明'), (1, '订阅号未认证'), (2, '订阅号已认证'), (3, '服务号未认证'), (4, '服务号已认证')], default=0, verbose_name='账号类别'),
        ),
    ]
