# Generated by Django 3.2.3 on 2022-08-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_wxaccountmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxPubAccountUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('open_id', models.CharField(db_index=True, max_length=150, verbose_name='OpenID')),
                ('union_id', models.CharField(db_index=True, max_length=150, verbose_name='union_id')),
                ('gender', models.SmallIntegerField(default=-1, verbose_name='性别')),
                ('subscribe_time', models.DateTimeField(default='', null=True, verbose_name='订阅时间')),
                ('remark', models.CharField(default='', max_length=100, null=True, verbose_name='备注')),
                ('subscribe_scene', models.CharField(db_index=True, default='', max_length=100, verbose_name='关注来源')),
                ('status', models.SmallIntegerField(choices=[(0, '已取关'), (1, '已关注')], verbose_name='关注状态')),
                ('pub_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wx.wxaccountmodel', verbose_name='所属公众号')),
            ],
            options={
                'verbose_name': '公众号用户管理',
                'verbose_name_plural': '公众号用户管理',
                'db_table': 'wx_account_user',
            },
        ),
        migrations.CreateModel(
            name='WxPubAccountTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tid', models.CharField(db_index=True, max_length=150, verbose_name='模板ID')),
                ('primary_industry', models.CharField(max_length=100, verbose_name='一级行业')),
                ('deputy_industry', models.CharField(max_length=100, verbose_name='二级行业')),
                ('title', models.CharField(max_length=100, verbose_name='模板标题')),
                ('content', models.CharField(max_length=100, verbose_name='模板内容')),
                ('pub_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='wx.wxaccountmodel', verbose_name='所属公众号')),
            ],
            options={
                'verbose_name': '消息模板管理',
                'verbose_name_plural': '消息模板管理',
                'db_table': 'wx_account_template',
            },
        ),
    ]
